export const HORSE_NAMES = [
  "Thunder Bolt",
  "Lightning Strike",
  "Storm Runner",
  "Fire Spirit",
  "Wind Dancer",
  "Silver Arrow",
  "Golden Flash",
  "Midnight Star",
  "Blazing Sun",
  "Ocean Wave",
  "Mountain Peak",
  "Desert Storm",
  "Forest King",
  "Ice Crystal",
  "Ruby Fire",
  "Diamond Dash",
  "Emerald Speed",
  "Sapphire Wind",
  "Black Beauty",
  "White Lightning",
] as const;

export const HORSE_COLORS = [
  "#FF6B6B",
  "#4ECDC4",
  "#45B7D1",
  "#96CEB4",
  "#FFEAA7",
  "#DDA0DD",
  "#98D8C8",
  "#F7DC6F",
  "#BB8FCE",
  "#85C1E9",
  "#F8C471",
  "#82E0AA",
  "#F1948A",
  "#85C1E9",
  "#D2B4DE",
  "#AED6F1",
  "#A3E4D7",
  "#F9E79F",
  "#FADBD8",
  "#D5DBDB",
] as const;
